"""change user id to bigint & correct bugs in models

Revision ID: 44301d61eea6
Revises: 1bad873fe975
Create Date: 2025-08-15 17:31:44.711487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44301d61eea6'
down_revision: Union[str, Sequence[str], None] = '1bad873fe975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
